services:
  xonotic-server:
    image: xonotic-server:arm64
    build: .
    container_name: xonotic-server
    restart: unless-stopped
    ports:
      - "26000:26000/udp"
      - "26000:26000"
    volumes:
      - xonotic-data:/opt/Xonotic/data

volumes:
  xonotic-data: